name: tests core 11

on:
  pull_request:

# **NOTE** that this workflow is kept to keep the ability to create CI status badges
# for other version branches, which needs the same file on the default branch. Nasty
# GitHub requirement.
jobs:
  code-quality:
    name: "code quality with core v11"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.4']
    steps:
      - name: dummy
        run: |
          echo "dummy"
