name: tests core 11

on:
  workflow_dispatch:

# **NOTE** that this workflow is kept to keep the ability to create CI status badges
# for other version branches, which needs the same file on the default branch. Nasty
# GitHub requirement.
jobs:
  dummy:
    name: "dummy v11 (disabled on main) to allow creation of badges for other branches"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
